# apiVersion: v1
# kind: Pod
# metadata:
#   name: webapp
#   labels:
#     label: webapp
#     release: "0"
# spec:
#   containers:
#   - name: webapp
#     image: richardchesterwood/k8s-fleetman-webapp-angular:release0

# ---

# #Using version to select a pod, using release type

#Writing a Pod without replica set
apiVersion: v1
kind: Pod
metadata:
  name: webapp-realease0-5
  labels:
    label: webapp
    release: "0-5"
spec:
  containers:
  - name: webapp-release0-5
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---

apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
    release: "0"
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1