#Writing a pod service
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    label: webapp
  ports:
  - name: http
    port: 80
    nodePort: 30030
  type: NodePort

# release "0-5" will select version of pod tag release "0-5"
--- 
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
  - name: http
    port: 8161
    nodePort: 30040
  type: NodePort