apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
# How do we want it implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs
provisioner: ebs.csi.aws.com
# volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4

# we wont specify how many space we want, it is dynamically allocated, base on what is claimed.