# Local storage configuration20

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: local
  capacity: 
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/web/mongo/"
    type: DirectoryOrCreate